[project]
name = "resourceportal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kshitijj-khandelwal", email = "kkhandelwal.ext@deloitte.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic>=2.13.5",
    "pyjwt>=2.13.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
resourceportal = "resourceportal:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
